# Generated by Django 4.1.4 on 2022-12-26 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_string', models.CharField(default='', max_length=50)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'unactivated_account_codes',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=30)),
                ('contact_id', models.IntegerField(blank=True, default=0)),
                ('is_first_login', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=30, unique=True)),
                ('activation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountactivation')),
            ],
        ),
    ]
