# Generated by Django 3.1.4 on 2021-03-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
