# Generated by Django 3.1.4 on 2021-01-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='filter_weights',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
