# Generated by Django 3.1.4 on 2021-02-24 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts_import', '0005_job_area'),
        ('search_history', '0003_contactviewhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactviewhistory',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_import.contact'),
        ),
        migrations.AlterField(
            model_name='contactviewhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
