# Generated by Django 3.1.4 on 2021-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdegree',
            name='user_contact_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
