# Generated by Django 3.1.4 on 2021-02-11 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts_import', '0002_contactdegree_user_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSocialPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_platform', models.CharField(max_length=50, null=True)),
                ('user_contact_id', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacts_social_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_social_platform', to='contacts_import.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts_social_platform',
            },
        ),
    ]
