# Generated by Django 3.1.4 on 2021-02-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_import', '0004_auto_20210211_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='area',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
